# ✨ GOGIDIX PLATFORM - ENTERPRISE MONITORING CONFIGURATION ✨
# Mission-Critical Observability Framework
# Architectural Excellence: Google Cloud Monitoring + Netflix Atlas Standards

# =====================================================
# SPRING ACTUATOR CONFIGURATION
# =====================================================
management:
  # Management Server Configuration
  server:
    port: ${MANAGEMENT_PORT:8081}
    address: ${MANAGEMENT_ADDRESS:0.0.0.0}
    servlet:
      context-path: ${MANAGEMENT_CONTEXT_PATH:/actuator}

  # Endpoints Configuration
  endpoints:
    web:
      # Base Path
      base-path: ${MANAGEMENT_BASE_PATH:/actuator}

      # Exposure
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_INCLUDE:health,info,metrics,prometheus,configprops,env,loggers,threaddump,heapdump,beans,conditions,refresh,circuitbreakers}
        exclude: ${MANAGEMENT_ENDPOINTS_EXCLUDE:}

      # CORS
      cors:
        allowed-origins: ${MANAGEMENT_CORS_ORIGINS:*}
        allowed-methods: ${MANAGEMENT_CORS_METHODS:GET,POST}
        allowed-headers: ${MANAGEMENT_CORS_HEADERS:*}

    # JMX Configuration
    jmx:
      exposure:
        include: ${MANAGEMENT_JMX_INCLUDE:*}

  # Health Check Configuration
  health:
    defaults:
      enabled: ${HEALTH_DEFAULTS_ENABLED:true}
    probes:
      enabled: ${HEALTH_PROBES_ENABLED:true}
    circuitbreakers:
      enabled: ${HEALTH_CIRCUIT_BREAKERS_ENABLED:true}
    ratelimiters:
      enabled: ${HEALTH_RATELIMITERS_ENABLED:true}
    mail:
      enabled: ${HEALTH_MAIL_ENABLED:false}
    redis:
      enabled: ${HEALTH_REDIS_ENABLED:true}
    datasource:
      enabled: ${HEALTH_DATASOURCE_ENABLED:true}
    livenessstate:
      enabled: ${HEALTH_LIVENESS_ENABLED:true}
    readinessstate:
      enabled: ${HEALTH_READINESS_ENABLED:true}

    # Group Configuration
    group:
      liveness:
        include: livenessState,diskSpace,ping
        show-details: ${HEALTH_LIVENESS_SHOW_DETAILS:always}
      readiness:
        include: readinessState,diskSpace,db
        show-details: ${HEALTH_READINESS_SHOW_DETAILS:always}
      external:
        include: db,redis,prometheus

    # Health Check Status Order
    status:
      order: ${HEALTH_STATUS_ORDER:DOWN,OUT_OF_SERVICE,UP,UNKNOWN}

  # Metrics Configuration
  metrics:
    # Global Settings
    enable:
      jvm: ${METRICS_JVM_ENABLED:true}
      system: ${METRICS_SYSTEM_ENABLED:true}
      log4j2: ${METRICS_LOG4J2_ENABLED:true}
      tomcat: ${METRICS_TOMCAT_ENABLED:true}
      cache: ${METRICS_CACHE_ENABLED:true}
      data: ${METRICS_DATA_ENABLED:true}
      web: ${METRICS_WEB_ENABLED:true}
      aop: ${METRICS_AOP_ENABLED:true}

    # Exporters
    export:
      # Prometheus
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}
        step: ${PROMETHEUS_STEP:30s}
        descriptions: ${PROMETHEUS_DESCRIPTIONS:true}
      # InfluxDB (optional)
      influx:
        enabled: ${INFLUX_ENABLED:false}
        uri: ${INFLUX_URI:http://localhost:8086/api/v1/metrics}
        db: ${INFLUX_DB:gogidix}
      # Atlas (Netflix)
      atlas:
        enabled: ${ATLAS_ENABLED:false}
        uri: ${ATLAS_URI:http://localhost:7101/api/v1/publish}

    # Distribution Configuration
    distribution:
      percentiles-histogram:
        http.server.requests: ${HTTP_PERCENTILES_HISTOGRAM:true}
        spring.data.repository.invocations: ${DATA_PERCENTILES_HISTOGRAM:true}
        cache: ${CACHE_PERCENTILES_HISTOGRAM:true}
      percentiles:
        http.server.requests: ${HTTP_PERCENTILES:0.5,0.9,0.95,0.99}
        spring.data.repository.invocations: ${DATA_PERCENTILES:0.5,0.9,0.95,0.99}
        cache: ${CACHE_PERCENTILES:0.5,0.9,0.95,0.99}
      sla:
        http.server.requests: ${HTTP_SLA:10ms,50ms,100ms,200ms,500ms}
        spring.data.repository.invocations: ${DATA_SLA:10ms,50ms,100ms,200ms}

    # Tags
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}
      version: ${project.version:1.0.0}
      region: ${gogidix.platform.region}
      instance_id: ${INSTANCE_ID:${random.uuid}}
      pod_name: ${POD_NAME:localhost}
      namespace: ${KUBERNETES_NAMESPACE:default}

    # Metrics Binders
    binders:
      jvm:
        enabled: ${METRICS_JVM_BINDER:true}
      logback:
        enabled: ${METRICS_LOGBACK_BINDER:true}
      processor:
        enabled: ${METRICS_PROCESSOR_BINDER:true}
      uptime:
        enabled: ${METRICS_UPTIME_BINDER:true}
      files:
        enabled: ${METRICS_FILES_BINDER:true}

    # Global Meter Registry Configuration
    global:
      registry:
        metrics:
          meter:
            # Prevent meter explosion
            maximum:
              expected:
                value: ${METRICS_MAXIMUM_EXPECTED_VALUE:1000}
            # Autocreation control
            type:
              distribution:
                histogram:
                  auto-timer:
                    percentiles: ${AUTO_TIMER_PERCENTILES:0.5,0.9,0.95}

  # Info Endpoint
  info:
    java:
      enabled: ${INFO_JAVA_ENABLED:true}
    os:
      enabled: ${INFO_OS_ENABLED:true}
    env:
      enabled: ${INFO_ENV_ENABLED:true}
    build:
      enabled: ${INFO_BUILD_ENABLED:true}
    git:
      mode: ${INFO_GIT_MODE:full}
    process:
      enabled: ${INFO_PROCESS_ENABLED:true}

  # Logging Configuration
  endpoint:
    loggers:
      enabled: ${LOGGERS_ENDPOINT_ENABLED:true}
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}

# =====================================================
# GOGIDIX PLATFORM MONITORING
# =====================================================
gogidix:
  platform:
    monitoring:
      # Metrics Configuration
      metrics:
        enabled: ${METRICS_ENABLED:true}

        # Business Metrics
        business:
          enabled: ${BUSINESS_METRICS_ENABLED:true}
          kpis:
            user-registrations: ${KPI_USER_REGISTRATIONS_ENABLED:true}
            property-listings: ${KPI_PROPERTY_LISTINGS_ENABLED:true}
            bookings: ${KPI_BOOKINGS_ENABLED:true}
            revenue: ${KPI_REVENUE_ENABLED:true}
            search-queries: ${KPI_SEARCH_QUERIES_ENABLED:true}

        # Performance Metrics
        performance:
          enabled: ${PERFORMANCE_METRICS_ENABLED:true}
          response-time:
            threshold: ${RESPONSE_TIME_THRESHOLD:1000} # ms
          error-rate:
            threshold: ${ERROR_RATE_THRESHOLD:0.05} # 5%
          throughput:
            threshold: ${THROUGHPUT_THRESHOLD:1000} # requests/min

        # System Metrics
        system:
          enabled: ${SYSTEM_METRICS_ENABLED:true}
          jvm:
            memory: ${JVM_MEMORY_METRICS:true}
            gc: ${JVM_GC_METRICS:true}
            threads: ${JVM_THREADS_METRICS:true}
          database:
            pool: ${DB_POOL_METRICS:true}
            query-time: ${DB_QUERY_METRICS:true}
          cache:
            hit-rate: ${CACHE_HIT_RATE_METRICS:true}
            size: ${CACHE_SIZE_METRICS:true}

      # Logging Configuration
      logging:
        # Structured Logging
        structured:
          enabled: ${STRUCTURED_LOGGING_ENABLED:true}
          format: ${LOG_FORMAT:json} # json, plain
          include-request-id: ${LOG_INCLUDE_REQUEST_ID:true}
          include-trace-id: ${LOG_INCLUDE_TRACE_ID:true}
          include-user-id: ${LOG_INCLUDE_USER_ID:true}

        # Log Levels
        levels:
          root: ${LOG_LEVEL_ROOT:INFO}
          com.gogidix: ${LOG_LEVEL_GOGIDIX:INFO}
          org.springframework: ${LOG_LEVEL_SPRING:WARN}
          org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}
          org.springframework.security: ${LOG_LEVEL_SECURITY:WARN}

        # Audit Logging
        audit:
          enabled: ${AUDIT_LOGGING_ENABLED:true}
          events:
            authentication: ${AUDIT_AUTH_EVENTS:true}
            authorization: ${AUDIT_AUTHZ_EVENTS:false}
            data-access: ${AUDIT_DATA_ACCESS:false}
            system-changes: ${AUDIT_SYSTEM_CHANGES:true}

        # Performance Logging
        performance:
          enabled: ${PERFORMANCE_LOGGING_ENABLED:false}
          slow-query-threshold: ${SLOW_QUERY_THRESHOLD:1000} # ms
          slow-endpoint-threshold: ${SLOW_ENDPOINT_THRESHOLD:2000} # ms

        # Error Logging
        errors:
          enabled: ${ERROR_LOGGING_ENABLED:true}
          include-stack-trace: ${ERROR_INCLUDE_STACK:true}
          max-stack-length: ${ERROR_MAX_STACK_LENGTH:1000}

      # Tracing Configuration
      tracing:
        enabled: ${TRACING_ENABLED:true}
        sampling:
          probability: ${TRACING_SAMPLING_PROBABILITY:0.1} # 10%
          rate-limiting:
            enabled: ${TRACING_RATE_LIMITING_ENABLED:true}
            max-operations-per-second: ${TRACING_MAX_OPS_PER_SECOND:100}

        # Zipkin Integration
        zipkin:
          enabled: ${ZIPKIN_ENABLED:false}
          base-url: ${ZIPKIN_BASE_URL:http://localhost:9411}
          service-name: ${spring.application.name}
          sender-type: ${ZIPKIN_SENDER:web}

        # Jaeger Integration
        jaeger:
          enabled: ${JAEGER_ENABLED:false}
          endpoint: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
          service-name: ${spring.application.name}
          sampler-type: ${JAEGER_SAMPLER:probabilistic}
          sampler-param: ${JAEGER_SAMPLER_PARAM:0.1}

        # AWS X-Ray Integration
        aws-xray:
          enabled: ${AWS_XRAY_ENABLED:false}
          daemon-address: ${AWS_XRAY_DAEMON:localhost:2000}
          service-name: ${spring.application.name}
          sampling-rule: ${AWS_XRAY_SAMPLING_RULE:default}

      # Health Check Configuration
      health:
        # Custom Health Checks
        custom:
          enabled: ${CUSTOM_HEALTH_CHECKS_ENABLED:true}
          checks:
            - name: database-connection
              class: com.gogidix.platform.monitoring.health.DatabaseHealthCheck
            - name: external-api
              class: com.gogidix.platform.monitoring.health.ExternalApiHealthCheck
              config:
                url: ${EXTERNAL_API_HEALTH_URL:}
                timeout: ${EXTERNAL_API_HEALTH_TIMEOUT:5000}

        # Health Check Thresholds
        thresholds:
          database:
            connection-pool-threshold: ${DB_HEALTH_POOL_THRESHOLD:80} # %
            response-time-threshold: ${DB_HEALTH_RESPONSE_TIME:500} # ms
          external-service:
            response-time-threshold: ${EXT_SERVICE_RESPONSE_TIME:1000} # ms
            error-rate-threshold: ${EXT_SERVICE_ERROR_RATE:0.05} # 5%

      # Alerting Configuration
      alerting:
        enabled: ${ALERTING_ENABLED:false}
        channels:
          email:
            enabled: ${ALERT_EMAIL_ENABLED:false}
            recipients: ${ALERT_EMAIL_RECIPIENTS:admin@gogidix.com}
            smtp-server: ${ALERT_SMTP_SERVER:smtp.gogidix.com}
            smtp-port: ${ALERT_SMTP_PORT:587}
          slack:
            enabled: ${ALERT_SLACK_ENABLED:false}
            webhook-url: ${ALERT_SLACK_WEBHOOK:}
            channel: ${ALERT_SLACK_CHANNEL:#alerts}
          pagerduty:
            enabled: ${ALERT_PAGERDUTY_ENABLED:false}
            integration-key: ${ALERT_PAGERDUTY_KEY:}
            severity: ${ALERT_PAGERDUTY_SEVERITY:critical}

        # Alert Rules
        rules:
          - name: high-error-rate
            condition: error_rate > 0.05
            duration: 5m
            severity: critical
          - name: high-response-time
            condition: response_time_p95 > 2000
            duration: 10m
            severity: warning
          - name: low-availability
            condition: availability < 0.99
            duration: 2m
            severity: critical
          - name: memory-usage-high
            condition: memory_usage > 0.9
            duration: 5m
            severity: warning

# =====================================================
# LOGGING CONFIGURATION
# =====================================================
logging:
  # Log Configuration
  config: classpath:logback-spring.xml

  # Log Levels
  level:
    # Application Logs
    com.gogidix: ${LOG_LEVEL_GOGIDIX:INFO}
    com.gogidix.platform: ${LOG_LEVEL_PLATFORM:DEBUG}

    # Spring Framework
    org.springframework: ${LOG_LEVEL_SPRING:INFO}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:WARN}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    org.springframework.cloud: ${LOG_LEVEL_SPRING_CLOUD:INFO}

    # Database
    org.hibernate: ${LOG_LEVEL_HIBERNATE:WARN}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BINDER:WARN}
    org.hibernate.tool.hbm2ddl: ${LOG_LEVEL_HIBERNATE_DDL:WARN}

    # Connection Pool
    com.zaxxer.hikari: ${LOG_LEVEL_HIKARI:WARN}

    # Messaging
    org.apache.kafka: ${LOG_LEVEL_KAFKA:WARN}
    org.springframework.kafka: ${LOG_LEVEL_SPRING_KAFKA:WARN}
    org.springframework.amqp: ${LOG_LEVEL_RABBITMQ:WARN}

    # Cache
    org.springframework.cache: ${LOG_LEVEL_CACHE:INFO}

    # Monitoring
    io.micrometer: ${LOG_LEVEL_MICROMETER:INFO}

    # Root Logger
    root: ${LOG_LEVEL_ROOT:INFO}

  # Log Pattern Configuration
  pattern:
    # Console Pattern
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-},%X{userId:-}] [%thread] %-5level [%logger{36}] - %msg%n"

    # File Pattern
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-},%X{userId:-}] [%thread] %-5level [%logger{36}] - %msg%n"

    # Rolling File Pattern
    rolling-file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-},%X{userId:-}] [%thread] %-5level [%logger{36}] - %msg%n"

  # File Logging
  file:
    # Main Log File
    name: ${LOG_FILE:logs/${spring.application.name}.log}

    # Rolling Policy
    max-size: ${LOG_FILE_MAX_SIZE:100MB}
    max-history: ${LOG_FILE_MAX_HISTORY:30}
    total-size-cap: ${LOG_FILE_TOTAL_SIZE_CAP:1GB}

    # Clean History on Startup
    clean-history-on-start: ${LOG_CLEAN_HISTORY_ON_START:false}

  # Logback Configuration
  logback:
    # Rolling Policy
    rollingpolicy:
      max-file-size: ${LOGBACK_MAX_FILE_SIZE:100MB}
      max-history: ${LOGBACK_MAX_HISTORY:30}
      total-size: ${LOGBACK_TOTAL_SIZE:1GB}
      file-name-pattern: ${LOGBACK_FILE_PATTERN:logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log}
      clean-history-on-start: ${LOGBACK_CLEAN_HISTORY:false}

# =====================================================
# ENVIRONMENT-SPECIFIC OVERRIDES
# =====================================================
---
# Development Environment
spring:
  config:
    activate:
      on-profile: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

gogidix:
  platform:
    monitoring:
      tracing:
        sampling:
          probability: 1.0 # 100% sampling for development

logging:
  level:
    com.gogidix: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG

---
# Test Environment
spring:
  config:
    activate:
      on-profile: test

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

gogidix:
  platform:
    monitoring:
      metrics:
        enabled: false
      tracing:
        enabled: false

logging:
  level:
    root: WARN

---
# Staging Environment
spring:
  config:
    activate:
      on-profile: staging

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

gogidix:
  platform:
    monitoring:
      metrics:
        enabled: true
        business:
          enabled: true
      tracing:
        sampling:
          probability: 0.01 # 1% sampling for staging

logging:
  level:
    root: INFO
    com.gogidix: INFO

---
# Production Environment
spring:
  config:
    activate:
      on-profile: prod

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never

gogidix:
  platform:
    monitoring:
      metrics:
        enabled: true
        business:
          enabled: true
        performance:
          enabled: true
        system:
          enabled: true
      logging:
        structured:
          enabled: true
        audit:
          enabled: true
        performance:
          enabled: true
      tracing:
        sampling:
          probability: 0.001 # 0.1% sampling for production
      health:
        custom:
          enabled: true
        thresholds:
          database:
            connection-pool-threshold: 90
            response-time-threshold: 200
          external-service:
            response-time-threshold: 500
            error-rate-threshold: 0.02
      alerting:
        enabled: true

logging:
  level:
    root: WARN
    com.gogidix: INFO
    org.springframework.security: WARN
    org.hibernate: WARN

---
# High-Traffic Production Environment
spring:
  config:
    activate:
      on-profile: high-traffic

# Reduced logging for performance
logging:
  level:
    root: ERROR
    com.gogidix: WARN

# Optimized metrics collection
management:
  metrics:
    export:
      prometheus:
        step: 60s # Reduce collection frequency

gogidix:
  platform:
    monitoring:
      metrics:
        distribution:
          percentiles:
            http.server.requests: 0.99 # Only P99 for high-traffic

# =====================================================
# CUSTOM MONITORING METRICS
# =====================================================
# Custom Timer Metrics
metrics.timers:
  http.server.requests:
    percentiles: 0.5,0.9,0.95,0.99
    percentiles-histogram: true
    sla: 10ms,50ms,100ms,200ms,500ms

  database.query.time:
    percentiles: 0.5,0.9,0.95,0.99
    percentiles-histogram: true
    sla: 5ms,10ms,50ms,100ms

  cache.get.time:
    percentiles: 0.5,0.9,0.95,0.99
    percentiles-histogram: true
    sla: 1ms,5ms,10ms

# Custom Gauge Metrics
metrics.gauges:
  jvm.memory.used:
    enabled: true
  database.connections.active:
    enabled: true
  http.sessions.active:
    enabled: true

# Custom Counter Metrics
metrics.counters:
  http.requests.total:
    enabled: true
  database.queries.total:
    enabled: true
  cache.hits.total:
    enabled: true