# ✨ GOGIDIX PLATFORM - GITHUB ACTIONS CI/CD PIPELINE ✨
# Mission-Critical Continuous Integration/Continuous Deployment Pipeline
# Architectural Excellence: Google Cloud Build + Netflix JenkinsX Standards

name: Build and Deploy Gogidix Platform Service

# =====================================================
# TRIGGER CONFIGURATION
# =====================================================
on:
  push:
    branches: [main, develop]
    tags: ['v*']

  pull_request:
    branches: [main, develop]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - staging
          - production

  schedule:
    # Nightly build for security scanning
    - cron: '0 2 * * *'
      if: github.ref == 'refs/heads/main'

# =====================================================
# ENVIRONMENT VARIABLES
# =====================================================
env:
  # Global configuration
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  JAVA_VERSION: '21'

  # Maven configuration
  MAVEN_OPTS: '-Xmx1024m'

  # Docker configuration
  DOCKER_BUILDKIT: 1
  DOCKER_BUILD_ARGS: |

# =====================================================
# PERMISSIONS
# =====================================================
permissions:
  contents: read
  packages: write
  deployments: write

# =====================================================
# GLOBAL VARIABLES
# =====================================================
variables:
  # Build configuration
  MAVEN_WRAPPER: './mvnw'
  MAVEN_OPTS: '-Xmx2048m'
  MAVEN_CLI_OPTS: '--batch-mode'

  # Docker configuration
  DOCKER_REGISTRY: ${{ secrets.REGISTRY_URL || env.REGISTRY }}
  DOCKER_NAMESPACE: ${{ secrets.REGISTRY_NAMESPACE || 'gogidix' }}
  DOCKER_IMAGE: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_NAMESPACE }}/${{ env.IMAGE_NAME }}'

  # Version configuration
  VERSION: ${{ github.ref == 'refs/heads/main' && 'latest' || github.ref_name || 'snapshot' }}
  SEMVER_VERSION: ${{ env.VERSION }}

  # Runtime configuration
  MEMORY_LIMIT: 2g
  CPU_LIMIT: '1'

# =====================================================
# JOBS
# =====================================================
jobs:
  # =====================================================
  # LINT AND VALIDATE
  # =====================================================
  lint-and-validate:
    name: 🧹 Lint and Validate
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: 🔍 Validate Gradle wrapper
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: gradle/wrapper-validation-action@v2

      - name: 🚀 Run Checkstyle
        run: ${{ env.MAVEN_WRAPPER }} checkstyle:check
        continue-on-error: true

      - name: 🛡️ Run SpotBugs
        run: ${{ env.MAVEN_WRAPPER }} spotbugs:check
        continue-on-error: true

      - name: 📊 Run PMD
        run: ${{ env.MAVEN_WRAPPER }} pmd:check
        continue-on-error: true

      - name: 📝 Upload lint results
        if: ${{ failure() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: target/site/sarif/lint-results.sarif

  # =====================================================
  # BUILD AND TEST
  # =====================================================
  build-and-test:
    name: 🔨 Build and Test
    runs-on: ubuntu-latest
    needs: lint-and-validate

    strategy:
      matrix:
        java-version: [21]
        os: [ubuntu-latest]

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: 📦 Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: 🧪 Run unit tests
        run: ${{ env.MAVEN_WRAPPER }} test -Dspring.profiles.active=test
        env:
          SPRING_PROFILES_ACTIVE: test
          DATABASE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          REDIS_HOST: localhost
          REDIS_PORT: 6379

      - name: 📸 Run integration tests
        run: ${{ env.MAVEN_WRAPPER }} verify -P integration-tests
        env:
          SPRING_PROFILES_ACTIVE: integration-test
          DATABASE_URL: jdbc:h2:mem:intdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

      - name: 🔍 Run security tests
        run: ${{ env.MAVEN_WRAPPER }} verify -P security-tests
        env:
          SPRING_PROFILES_ACTIVE: security-test

      - name: 📊 Generate Test Report
        if: ${{ always() }}
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests (Java ${{ matrix.java-version }})
          path: target/surefire-reports
          reporter: java-junit
          fail-on-error: true

      - name: 📤 Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./target/site/jacoco/jacoco.xml
          flags: unittests
          name: codecov-umbrella

  # =====================================================
  # SECURITY SCAN
  # =====================================================
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: 🔐 Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Gogidix Platform Service'
          path: '.'
          format: 'HTML'

      - name: 🔐 Run Snyk Security Scan
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=results.sarif

      - name: 🔐 Upload Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.build.outputs.image-id }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: 📤 Upload security scan results
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  # =====================================================
  # BUILD DOCKER IMAGE
  # =====================================================
  build-image:
    name: 🐳 Build Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🏷️ Set up Docker BuildKit
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 📋 Extract Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 🏗️ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ env.DOCKER_BUILD_ARGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 📋 Extract Image Metadata
        if: ${{ github.event_name != 'pull_request' }}
        id: image-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}:${{ env.VERSION }}

  # =====================================================
  # DEPLOY TO STAGING
   helper/setup-helm@v3
        with:
          version: 'v3.12.1'

      - name: 🔧 Configure Helm
        run: |
          helm repo add staging ${{ secrets.STAGING_REPO_URL }} \
            --username ${{ secrets.STAGING_REPO_USERNAME }} \
            --password ${{ secrets.STAGING_REPO_PASSWORD }}
          helm repo update

      - name: 🎯 Deploy to Staging
        run: |
          helm upgrade --install gogidix-${{ github.event.repository.owner }}-${{ github.event.repository.name }}-staging \
            staging/${{ github.event.repository.owner }}-${{ github.event.repository.name }} \
            --namespace staging \
            --values charts/values-staging.yaml \
            --set image.repository=${{ env.DOCKER_IMAGE }} \
            --set image.tag=${{ env.VERSION }} \
            --set environment=staging \
            --set service.targetPort=8080 \
            --set ingress.enabled=true \
            --set ingress.host=${{ secrets.STAGING_DOMAIN }}

      - name: ⏳️ Wait for Deployment
        run: |
          kubectl wait --for=condition=available deployment/gogidix-${{ github.event.repository.owner }}-${{ github.event.repository.name }}-staging --namespace=staging --timeout=300s

      - name: 🧪 Run Smoke Tests
        run: |
          ./scripts/smoke-tests.sh staging ${{ secrets.STAGING_DOMAIN }}

      -name: 🔔 Notify Slack (Success)
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            🚀 Deployment to staging successful!
            Service: ${{ github.repository }}
            Version: ${{ env.VERSION }}
            URL: https://${{ secrets.STAGING_DOMAIN }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 🔔 Notify Slack (Failure)
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            ❌ Deployment to staging failed!
            Service: ${{ github.repository }}
            Version: ${{ env.VERSION }}
            Check GitHub Actions for details.
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  # =====================================================
  # DEPLOY TO PRODUCTION
  # =====================================================
  deploy-production:
    name: 🚀 Deploy to Production
    runs-on: ubuntu-latest
    needs: [build-image, security-scan]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: ☕ Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: 🔑 Setup Kubernetes Config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: 📚 Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.1'

      - name: 🔧 Configure Helm
        run: |
          helm repo add production ${{ secrets.PRODUCTION_REPO_URL }} \
            --username ${{ secrets.PRODUCTION_REPO_USERNAME }} \
            --password ${{ secrets.PRODUCTION_REPO_PASSWORD }}
          helm repo update

      - name: 🎯 Deploy to Production
        run: |
          helm upgrade --install gogidix-${{ github.event.repository.owner }}-${{ github.event.repository.name }}-prod \
            production/${{ github.event.repository.owner }}-${{ github.event.repository.name }} \
            --namespace production \
            --values charts/values-production.yaml \
            --set image.repository=${{ env.DOCKER_IMAGE }} \
            --set image.tag=${{ env.VERSION }} \
            --set environment=production \
            --set replicaCount=3 \
            --set resources.requests.memory=4Gi \
            --set resources.limits.memory=8Gi \
            --set service.targetPort=8080 \
            --set ingress.enabled=true \
            --set ingress.host=${{ secrets.PRODUCTION_DOMAIN }} \
            --set autoscaling.enabled=true \
            --set autoscaling.minReplicas=3 \
            --set autoscaling.maxReplicas=10 \
            --set autoscaling.targetCPUUtilization=70

      - name: ⏳️ Wait for Deployment
        run: |
          kubectl wait --for=condition=available deployment/gogidix-${{ github.event.repository.owner }}-${{ github.event.repository.name }}-prod --namespace=production --timeout=600s

      - name: 🔍 Run Health Checks
        run: |
          ./scripts/health-check.sh production ${{ secrets.PRODUCTION_DOMAIN }}

      - name: 📊 Generate Deployment Report
        run: |
          ./scripts/deployment-report.sh production ${{ env.VERSION }}

      - name: 🏷️ Create Release Tag
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            🎯 Production Deployment
            Service: ${{ github.repository }}
            Version: ${{ env.VERSION }}
            Date: ${{ github.event.head_commit.timestamp }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: 🔔 Notify Slack (Success)
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: |
            🎉 Production deployment successful!
            Service: ${{ github.repository }}
            Version: ${{ env.VERSION }}
            URL: https://${{ secrets.PRODUCTION_DOMAIN }}
            Release: ${{ env.VERSION }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 🔔 Notify PagerDuty (Success)
        if: ${{ success() && secrets.PAGERDUTY_KEY != '' }}
        uses: pagerduty/pagerduty-action@v1
        with:
          integration_key: ${{ secrets.PAGERDUTY_KEY }}
          trigger_id: ${{ github.repository }}-{{ github.sha }}
          severity: info
          dedup_key: ${{ github.repository }}-${{ github.sha }}
          summary: "Production deployment successful for ${{ github.repository }} v${{ env.VERSION }}"

      - name: 🔔 Notify Slack (Failure)
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: |
            ❌ Production deployment failed!
            Service: ${{ github.repository }}
            Version: ${{ env.VERSION }}
            Check GitHub Actions for details.
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 🔔 Notify PagerDuty (Failure)
        if: ${{ failure() && secrets.PAGERDUTY_KEY != '' }}
        uses: pagerduty/pagerduty-action@v1
        with:
          integration_key: ${{ secrets.PAGERDUTY_KEY }}
          trigger_id: ${{ github.repository }}-{{ github.sha }}
          severity: critical
          dedup_key: ${{ github.repository }}-${{ github.sha }}
          summary: "Production deployment FAILED for ${{ github.repository }} v${{ env.VERSION }}"

  # =====================================================
  # CLEANUP
  # =====================================================
  cleanup:
    name: 🧹 Cleanup
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == false

    steps:
      - name: 🧹 Remove Docker Image
        if: ${{ env.DOCKER_IMAGE && github.event_name == 'pull_request' }}
        run: |
          docker rmi ${{ env.DOCKER_IMAGE }}:pr-${{ github.event.number }} || true
          docker rmi ${{ env.DOCKER_IMAGE }}:latest-pr || true

# =====================================================
# WORKFLOW NOTIFICATIONS
# =====================================================
notifications:
  email:
    if: ${{ failure() && secrets.ADMIN_EMAIL != '' }}
    to: ${{ secrets.ADMIN_EMAIL }}
    from: github-actions@noreply.github.com
    subject: 🚨 Gogidix Platform CI/CD Failed - ${{ github.repository }}

  slack:
    if: ${{ failure() && secrets.SLACK_WEBHOOK_URL != '' }}
    uses: 8398a7/action-slack@v3
    with:
      status: failure
      text: |
        ❌ GitHub Actions workflow failed!
        Repository: ${{ github.repository }}
        Workflow: ${{ github.workflow }}
        Branch: ${{ github.ref_name }}
        Actor: ${{ github.actor }}
        Check GitHub Actions for details.
      webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}