# ✨ GOGIDIX PLATFORM - PRODUCTION ENVIRONMENT PROFILE ✨
# Mission-Critical Production Configuration
# Optimized for security, performance, and reliability

spring:
  profiles:
    active: prod

  # =====================================================
  # DATABASE CONFIGURATION - PRODUCTION
  # =====================================================
  datasource:
    url: ${PROD_DB_URL:jdbc:postgresql://prod-db:5432/gogidix_prod}
    username: ${PROD_DB_USERNAME:gogidix_prod}
    password: ${PROD_DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 30000
      pool-name: ${spring.application.name}-prod-pool

      # Production SSL Configuration
      data-source-properties:
        ssl: ${DB_SSL_ENABLED:true}
        sslmode: ${DB_SSL_MODE:require}
        sslfactory: ${DB_SSL_FACTORY:org.postgresql.ssl.DefaultJavaSSLFactory}
        sslcert: ${DB_SSL_CERT:}
        sslkey: ${DB_SSL_KEY:}
        sslrootcert: ${DB_SSL_ROOT_CERT:}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 50
        order_inserts: true
        order_updates: true
      connection:
        provider_disables_autocommit: true
    show-sql: false
    open-in-view: false

  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    locations:
      - classpath:db/migration
      - classpath:db/migration/prod

  # =====================================================
  # REDIS CONFIGURATION - PRODUCTION
  # =====================================================
  data:
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:5000ms}
      ssl: ${REDIS_SSL_ENABLED:true}

      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: ${REDIS_POOL_MAX_WAIT:5000ms}
          time-between-eviction-runs: 30000
          min-evictable-idle-time: 60000

  # =====================================================
  # CACHE CONFIGURATION - PRODUCTION
  # =====================================================
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:PT10M}
      key-prefix: ${CACHE_KEY_PREFIX:gogidix:}
      use-key-prefix: true
      cache-null-values: false

  # =====================================================
  # SECURITY CONFIGURATION - PRODUCTION
  # =====================================================
  security:
    csrf:
      enabled: true
      token-repository: httpSession
      require-csrf-protection: true

  session:
    store-type: redis
    timeout: 1800 # 30 minutes
    cookie:
      name: GOGIDIX-SESSION
      http-only: true
      secure: true
      same-site: strict
      max-age: 1800

  gogidix:
    platform:
      security:
        jwt:
          secret: ${GOGIDIX_JWT_SECRET} # Must be set from environment
          issuer: ${JWT_ISSUER:https://auth.gogidix.com}
          audience: gogidix-users
          access-token-expiration: PT15M # Short-lived access tokens
          refresh-token-expiration: P3D
          remember-me-token-expiration: P30D
          rotation-enabled: true
          rotation-grace-period: PT5M
          algorithm: HS256

        password:
          argon2:
            memory: 131072 # 128MB - increased for production
            parallelism: 6
            iterations: 5
          policies:
            min-length: 12
            max-length: 64
            require-uppercase: true
            require-lowercase: true
            require-digits: true
            require-special: true
            forbid-whitespace: true
            prevent-common-passwords: true

        rate-limit:
          enabled: true
          global:
            requests-per-minute: 100
            burst-capacity: 200
          endpoints:
            authentication:
              login:
                requests-per-minute: 10
                burst-capacity: 20
              registration:
                requests-per-minute: 5
                burst-capacity: 10
              password-reset:
                requests-per-minute: 3
                burst-capacity: 5
            api:
              public:
                requests-per-minute: 60
              authenticated:
                requests-per-minute: 1000
              premium:
                requests-per-minute: 5000

        rbac:
          enabled: true
          cache-enabled: true
          cache-ttl: PT1M # Short TTL for production

        encryption:
          master-key: ${ENCRYPTION_MASTER_KEY} # Must be set from KMS
          rotation-interval: P30D
          algorithm: AES-256-GCM

        audit:
          enabled: true
          level: WARN
          retention-days: 2550 # 7 years
          storage: database
          events:
            authentication: true
            authorization: true
            data-access: true
            system-changes: true

        mfa:
          enabled: true
          required-for-roles: USER,AGENT,ADMIN,MODERATOR,PROPERTY_MANAGER,SYSTEM_ADMIN,SUPER_ADMIN
          issuer: Gogidix Platform
          time-window: 60

        sessions:
          max-concurrent-sessions: 3
          prevent-concurrent-login: true
          session-fixation-protection: migrateSession

  # =====================================================
  # MESSAGING CONFIGURATION - PRODUCTION
  # =====================================================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:prod-kafka-1:9092,prod-kafka-2:9092,prod-kafka-3:9092}
    producer:
      acks: all
      retries: 5
      enable-idempotence: true
      transaction-id-prefix: ${spring.application.name}-prod-tx-
      batch-size: 32768
      linger-ms: 10
      compression-type: lz4

    consumer:
      group-id: ${spring.application.name}-prod-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      max-poll-interval: 300000
      fetch-min-bytes: 1
      fetch-max-bytes: 52428800
      isolation:
        level: read_committed

  rabbitmq:
    host: ${RABBITMQ_HOST:prod-rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:gogidix-prod}
    password: ${RABBITMQ_PASSWORD:}
    virtual-host: ${RABBITMQ_VHOST:gogidix-prod}
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true

  gogidix:
    platform:
      messaging:
        event-bus:
          enabled: true
          persistence:
            enabled: true
          dead-letter-queue:
            enabled: true
        message-queue:
          backend: kafka
          retry:
            max-attempts: 5
            initial-delay: 2000
          dead-letter:
            enabled: true
            ttl: P7D

  # =====================================================
  # MONITORING CONFIGURATION - PRODUCTION
  # =====================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
      cors:
        allowed-origins: ${MANAGEMENT_CORS_ORIGINS:https://admin.gogidix.com}
        allowed-methods: GET,POST
        allowed-headers: Authorization,Content-Type

  endpoint:
    health:
      show-details: never
      roles: ADMIN

  metrics:
    export:
      prometheus:
        enabled: true
        step: 30s

  gogidix:
    platform:
      monitoring:
        metrics:
          enabled: true
          business:
            enabled: true
          performance:
            enabled: true
          system:
            enabled: true
        tracing:
          sampling:
            probability: 0.001 # 0.1% sampling
        logging:
          structured:
            enabled: true
          audit:
            enabled: true
          performance:
            enabled: false # Disabled in production for performance
        health:
          custom:
            enabled: true
          thresholds:
            database:
              connection-pool-threshold: 90
              response-time-threshold: 200
            external-service:
              response-time-threshold: 500
              error-rate-threshold: 0.02
        alerting:
          enabled: true
          channels:
            email:
              enabled: true
              recipients: ${ALERT_EMAIL_RECIPIENTS}
            slack:
              enabled: ${ALERT_SLACK_ENABLED:false}
              webhook-url: ${ALERT_SLACK_WEBHOOK}
            pagerduty:
              enabled: ${ALERT_PAGERDUTY_ENABLED:false}
              integration-key: ${ALERT_PAGERDUTY_KEY}

  # =====================================================
  # LOGGING CONFIGURATION - PRODUCTION
  # =====================================================
logging:
  level:
    root: WARN
    com.gogidix: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.springframework.kafka: WARN

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level [%logger{36}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId:-},%X{spanId:-}] [%thread] %-5level [%logger{36}] - %msg%n"

  file:
    name: /var/log/gogidix/${spring.application.name}/${spring.application.name}.log
    max-size: 500MB
    max-history: 60
    total-size-cap: 10GB

  # =====================================================
  # SERVER CONFIGURATION - PRODUCTION
  # =====================================================
server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    min-spare-threads: 20
    accept-count: 100
    connection-timeout: 20000
    max-connections: 8192
    redirect-enabled: true
    accesslog:
      enabled: true
      pattern: "%h %l %u %t "%r" %s %b %D %{User-Agent}i"
      directory: /var/log/tomcat/access

  # =====================================================
  # PRODUCTION SPECIFIC CONFIGURATION
  # =====================================================
  # Async Configuration
  spring.task.execution:
    pool:
      core-size: 8
      max-size: 32
      queue-capacity: 100
      keep-alive: 60s
    thread-name-prefix: ${spring.application.name}-async-

  # Scheduled Tasks
  spring.task.scheduling:
    pool:
      size: 4
    thread-name-prefix: ${spring.application.name}-scheduled-

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL
    time-zone: UTC

  # =====================================================
  # PRODUCTION FEATURE FLAGS
  # =====================================================
gogidix:
  platform:
    features:
      property-search: true
      user-profiles: true
      booking-system: true
      payment-processing: true
      messaging-system: true
      analytics-dashboard: true
      mobile-api: true
      graphql-api: false
      webhooks: true

    external-services:
      payment:
        provider: ${PAYMENT_PROVIDER:stripe}
        api-key: ${PAYMENT_API_KEY}
        environment: production
        timeout: PT30S
      notification:
        email-provider: ${EMAIL_PROVIDER:sendgrid}
        sms-provider: ${SMS_PROVIDER:twilio}
        email-api-key: ${EMAIL_API_KEY}
        sms-api-key: ${SMS_API_KEY}
        queue-enabled: true
      geocoding:
        provider: ${GEOCODING_PROVIDER:google}
        api-key: ${GEOCODING_API_KEY}
        cache-ttl: PT24H
        max-requests-per-minute: 100

# =====================================================
# PRODUCTION PERFORMANCE TUNING
# =====================================================
# JVM Options (typically set via environment variables)
# JAVA_OPTS="-Xms2g -Xmx4g -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+OptimizeStringConcat"

# Application Performance
spring:
  jpa:
    properties:
      hibernate:
        # Connection Pool
        hibernate.connection.provider_disables_autocommit: true
        # Query Optimization
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: false
        # Batch Processing
        hibernate.jdbc.batch_size: 50
        hibernate.order_inserts: true
        hibernate.order_updates: true
        hibernate.jdbc.batch_versioned_data: true

# =====================================================
# PRODUCTION SECURITY HARDENING
# =====================================================
# Security Headers (configured via Spring Security)
# Content Security Policy
security.headers.csp.policy: "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self'; frame-ancestors 'none';"

# HTTP Strict Transport Security
security.headers.hsts.enabled: true
security.headers.hsts.max-age: 31536000
security.headers.hsts.include-subdomains: true

# Clickjacking Protection
security.headers.frame-options.mode: DENY

# XSS Protection
security.headers.xss-protection.mode: block

# =====================================================
# PRODUCTION BACKUP AND DISASTER RECOVERY
# =====================================================
backup:
  enabled: ${BACKUP_ENABLED:true}
  schedule: ${BACKUP_SCHEDULE:0 2 * * * *} # Daily at 2 AM
  retention: ${BACKUP_RETENTION:30} # Days
  storage: ${BACKUP_STORAGE:s3} # local, s3, gcs

disaster:
  recovery:
    enabled: ${DISASTER_RECOVERY_ENABLED:false}
    failover-url: ${FAILOVER_URL:https://backup.gogidix.com}
    health-check-interval: 30